get http://localhost:3000/api/geotags

###

post http://localhost:3000/api/geotags
Content-Type: application/json

{ 
    "name": "New Place", 
    "latitude": 48.88838, 
    "longitude": 8.7008,
    "hashtag": "#NewPlace"
}

###

get http://localhost:3000/api/geotags/12

###

put http://localhost:3000/api/geotags/12
Content-Type: application/json

{
    "name": "Updated Place", 
    "latitude": 48.18838, 
    "longitude": 8.9008, 
    "hashtag": "#UpdatedPlace"
}

###
delete http://localhost:3000/api/geotags/12